export const dados = [
    {
      "id": 1,
      "horaInicio": "12:00:00",
      "nomeProva": "Marco viadão",
      "horaTermino": '12: 10: 00',
      "qtdQuestoesMatematica": 5,
      "qtdQuestoesPortugues": 5,
      "qtdQuestoesInformatica": 5,
      "qtdQuestoesConhecimentosGerais": 5,
      "token": '9241',
      "status": "Aberta",
      "porcentagemAprovacao": 60,
      "dataRealizacao": '2222-02-22',
      "vagasDisponiveis": 10,
      "qtdAprovados": null,
      "mediaGeral": null,
    },
    {
      "id": 2,
      "horaInicio": "12:00:00",
      "nomeProva": "Marco viadão",
      "horaTermino": '12: 10: 00',
      "qtdQuestoesMatematica": 5,
      "qtdQuestoesPortugues": 5,
      "qtdQuestoesInformatica": 5,
      "qtdQuestoesConhecimentosGerais": 5,
      "token": '9241',
      "status": "Aberta",
      "porcentagemAprovacao": 60,
      "dataRealizacao": '2222-02-22',
      "vagasDisponiveis": 10,
      "qtdAprovados": null,
      "mediaGeral": null,
    },
    {
      "id": 3,
      "horaInicio": "12:00:00",
      "nomeProva": "Marco viadão",
      "horaTermino": '12: 10: 00',
      "qtdQuestoesMatematica": 5,
      "qtdQuestoesPortugues": 5,
      "qtdQuestoesInformatica": 5,
      "qtdQuestoesConhecimentosGerais": 5,
      "token": '9241',
      "status": "Aberta",
      "porcentagemAprovacao": 60,
      "dataRealizacao": '2222-02-22',
      "vagasDisponiveis": 10,
      "qtdAprovados": null,
      "mediaGeral": null,
    },
    {
      "id": 4,
      "horaInicio": "12:00:00",
      "nomeProva": "Marco viadão",
      "horaTermino": '12: 10: 00',
      "qtdQuestoesMatematica": 5,
      "qtdQuestoesPortugues": 5,
      "qtdQuestoesInformatica": 5,
      "qtdQuestoesConhecimentosGerais": 5,
      "token": '9241',
      "status": "Aberta",
      "porcentagemAprovacao": 60,
      "dataRealizacao": '2222-02-22',
      "vagasDisponiveis": 10,
      "qtdAprovados": null,
      "mediaGeral": null,
    },
  ];
